### ISSUE TITLE
Error importing gsearch

### ISSUE THREAD

**Issue by SimplyPancake** [aviaryan/python-gsearch#9]
Tested on both Windows & MacOs

`from gsearch import googlesearch

results = search('Hallo!', num_results=20)

print(results)`

> Traceback (most recent call last):
  File ".\gsearch.py", line 1, in <module>
    from gsearch import googlesearch
  File "C:\Users\Daniel\Desktop\Qarebase\gsearch.py", line 1, in <module>
    from gsearch import googlesearch
ImportError: cannot import name 'googlesearch' from 'gsearch' (C:\Users\Daniel\Desktop\Qarebase\gsearch.py)

**Comment by aviaryan** [comment]
Hey, please import like this

```py
from gsearch.googlesearch import search
```

See https://github.com/aviaryan/python-gsearch#using

**Comment by SimplyPancake** [comment]
Thanks!
